name: Publish Docker image

on:
  push:
    branches:
      - main

jobs:
  push_to_registry:
    runs-on: ubuntu-latest
    steps:
      # 1、检出代码
      - name: Checkout repo
        uses: actions/checkout@v3

      # 2、登录 Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 3、构建并推送
      - name: Build and push Docker image as :latest
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          # 直接把 latest 写死
          tags: |
            docker.io/ywtm/proxy_pool_new:latest
          # (可选) 如果你需要多平台构建：
          # platforms: linux/amd64,linux/arm64
